# Generated by Django 2.2 on 2019-07-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190719_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
