# Generated by Django 2.2 on 2019-07-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190727_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Comments'),
        ),
    ]
