# Generated by Django 2.2 on 2019-07-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comments_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
    ]
