"""
Django settings for zl_prac project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2&p-k0^cjnrq8b&^r3-#=^8*=$v!$akgrt(3%bg0m+qjtmtbp)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.news',
    'apps.course',
    'apps.cms',
    'apps.xfz_auth',
    'rest_framework',
    'debug_toolbar',
    'haystack',
]

HAYSTACK_CONNECTIONS={
    'default': {
        'ENGINE': 'apps.news.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),#告诉引擎索引文件的存放位置，记得要创建whoosh_index这个文件夹
    },
}






MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zl_prac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front', 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': ['django.templatetags.static'],
        },
    },
]

WSGI_APPLICATION = 'zl_prac.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xfz',  # 要连接的数据库，连接前需要创建好
        'USER': 'zhang',  # 连接数据库的用户名
        'PASSWORD': '111',  # 连接数据库的密码
        'HOST': '127.0.0.1',  # 连接主机，默认本级
        'PORT': 3306  # 端口 默认3306
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',  # 指定memcached位置
    }
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front', "dis"),
]

# 用户文件存放位置
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 指定User模型
AUTH_USER_MODEL = 'xfz_auth.User'

# 如果末尾不带‘/’的url为匹配到，则自动添加‘/’
APPEND_SLASH = True

# 默认情况下，新闻管理页每页显示新闻条目数
page_num = [5, 10, 20, 50]

# 默认情况下，新闻index每次加载数量个数
news_num = 2

# debug-toolbar
INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]
DEBUG_TOOLBAR_PANELS = [
    # 'debug_toolbar.panels.versions.VersionsPanel',#django版本
    'debug_toolbar.panels.timer.TimerPanel',  # 时间
    # 'debug_toolbar.panels.settings.SettingsPanel',#django setting配置
    # 'debug_toolbar.panels.headers.HeadersPanel',#请求/回复头信息
    # 'debug_toolbar.panels.request.RequestPanel',#请求信息
    'debug_toolbar.panels.sql.SQLPanel',  # 数据库相关
    # 'debug_toolbar.panels.staticfiles.StaticFilesPanel',#静态文件
    # 'debug_toolbar.panels.templates.TemplatesPanel',#模板
    # 'debug_toolbar.panels.cache.CachePanel',#缓存
    # 'debug_toolbar.panels.signals.SignalsPanel',#信号机制
    # 'debug_toolbar.panels.logging.LoggingPanel',#
    # 'debug_toolbar.panels.redirects.RedirectsPanel',#重定向
    # 'debug_toolbar.panels.profiling.ProfilingPanel',
]
DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': ''
}
