# Generated by Django 2.2 on 2019-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('link_url', models.URLField()),
                ('banner_img', models.URLField()),
            ],
        ),
    ]
